services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    labels:
      - docker-volume-backup.stop-during-backup=true
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    stop_grace_period: 600s
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=32
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ=UTC
      - COMMUNITY=true
      - SERVER_NAME="Jephs-World-of-Pals"
      - SERVER_DESCRIPTION="The-best-Palworld-server-on-the-surface-net!"
      - AUTO_UPDATE_ENABLED=true
      - AUTO_UPDATE_WARN_MINUTES=5
      - AUTO_UPDATE_CRON_EXPRESSION=30 */1 * * *
      - BACKUP_ENABLED=false
      - PAL_EGG_DEFAULT_HATCHING_TIME=2.0
    env_file: ./palworld.env
    volumes:
      - ./palworld:/palworld/
  backup:
    image: offen/docker-volume-backup:v2.35.0
    restart: unless-stopped
    environment:
      - BACKUP_CRON_EXPRESSION=0 */3 * * *
      - BACKUP_COMPRESSION=gz
      - GZIP_PARALLELISM=0
      - BACKUP_RETENTION_DAYS=14
    env_file: ./backup.env
    volumes:
      - ./palworld:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
